const CACHE_NAME = 'mixbox-v1';

const ALL_ASSETS = [
  './',
  './index.html',
  './Css/style.css',
  './JS/script.js',
  './assets/chapters.js',
  './JSON/manifest.json',
  './Icon/beat.png',
  'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;700&display=swap',

  // Chapter 1
  'assets/sounds/chapter1/1-01__Lead_A.mp3',
  'assets/sounds/chapter1/1-02__Deux_A.mp3',
  'assets/sounds/chapter1/1-03__Kosh_A.mp3',
  'assets/sounds/chapter1/1-04__Shpok_A.mp3',
  'assets/sounds/chapter1/1-05__Tom_A.mp3',
  'assets/sounds/chapter1/1-06__Nouana_A.mp3',
  'assets/sounds/chapter1/1-07__Scratch_A.mp3',
  'assets/sounds/chapter1/1-08__Trill_A.mp3',
  'assets/sounds/chapter1/1-09__Bass_A.mp3',
  'assets/sounds/chapter1/1-10__Uh_A.mp3',
  'assets/sounds/chapter1/1-11__Nugu_A.mp3',
  'assets/sounds/chapter1/1-12__Guit_A.mp3',
  'assets/sounds/chapter1/1-13__Tromp_A.mp3',
  'assets/sounds/chapter1/1-14__Pouin_A.mp3',
  'assets/sounds/chapter1/1-15__Tung_A.mp3',
  'assets/sounds/chapter1/1-16__Aoun_A.mp3',
  'assets/sounds/chapter1/1-17__Hum_A.mp3',
  'assets/sounds/chapter1/1-18__Get_A.mp3',
  'assets/sounds/chapter1/1-19__Tellme_A.mp3',
  'assets/sounds/chapter1/1-20__Make_A.mp3',
  'assets/sounds/chapter1/1-21__Bonus-Choir.mp3',
  'assets/sounds/chapter1/1-22__Predrop-Sailor.mp3',
  'assets/sounds/chapter1/1-23__Bonus-Sailor.mp3',
  'assets/sounds/chapter1/1-24__Predrop-Santa.mp3',
  'assets/sounds/chapter1/1-25__Bonus-Santa.mp3',

  // Chapter 2
  'assets/sounds/chapter2/2-01__Beat1_Boom_A.mp3',
  'assets/sounds/chapter2/2-02__Beat1_Boom_B.mp3',
  'assets/sounds/chapter2/2-03__Beat2_Kashi_A.mp3',
  'assets/sounds/chapter2/2-04__Beat2_Kashi_B.mp3',
  'assets/sounds/chapter2/2-05__Beat3_Paomeu_A.mp3',
  'assets/sounds/chapter2/2-06__Beat4_Ptttpeu_A.mp3',
  'assets/sounds/chapter2/2-07__Beat4_Ptttpeu_B.mp3',
  'assets/sounds/chapter2/2-08__Beat5_Slupttt_A.mp3',
  'assets/sounds/chapter2/2-09__Effet1_Poulll_A.mp3',
  'assets/sounds/chapter2/2-10__Effet1_Poulll_B.mp3',
  'assets/sounds/chapter2/2-11__Effet2_Tucati_A.mp3',
  'assets/sounds/chapter2/2-12__Effet3_Tuilopta_A.mp3',
  'assets/sounds/chapter2/2-13__Effet3_Tuilopta_B.mp3',
  'assets/sounds/chapter2/2-14__Effet4_Tululou_A.mp3',
  'assets/sounds/chapter2/2-15__Effet5_Tumttt_A.mp3',
  'assets/sounds/chapter2/2-16__Effet5_Tumttt_B.mp3',
  'assets/sounds/chapter2/2-17__Melo1_Nananana_A.mp3',
  'assets/sounds/chapter2/2-18__Melo1_Nananana_B.mp3',
  'assets/sounds/chapter2/2-19__Melo2_Pelulu_A.mp3',
  'assets/sounds/chapter2/2-20__Melo2_Pelulu_B.mp3',
  'assets/sounds/chapter2/2-21__Melo3_Siffle_A.mp3',
  'assets/sounds/chapter2/2-22__Melo3_Siffle_B.mp3',
  'assets/sounds/chapter2/2-23__Melo4_Tatouti_A.mp3',
  'assets/sounds/chapter2/2-24__Melo4_Tatouti_B.mp3',
  'assets/sounds/chapter2/2-25__Melo5_Tvutvutvu_A.mp3',
  'assets/sounds/chapter2/2-26__Melo5_Tvutvutvu_B.mp3',
  'assets/sounds/chapter2/2-27__Coeur1_Oaaah_A.mp3',
  'assets/sounds/chapter2/2-28__Coeur1_Oaaah_B.mp3',
  'assets/sounds/chapter2/2-29__Coeur2_Cougou_A.mp3',
  'assets/sounds/chapter2/2-30__Coeur2_Cougou_B.mp3',
  'assets/sounds/chapter2/2-31__Coeur3_Porticoeur_A.mp3',
  'assets/sounds/chapter2/2-32__Coeur3_Porticoeur_B.mp3',
  'assets/sounds/chapter2/2-33__Voix1_Isit_A.mp3',
  'assets/sounds/chapter2/2-34__Voix1_Isit_B.mp3',
  'assets/sounds/chapter2/2-35__Voix2_Uare_A.mp3',
  'assets/sounds/chapter2/2-36__Voix2_Uare_B.mp3',
  'assets/sounds/chapter2/2-37__Predrop.mp3',
  'assets/sounds/chapter2/2-38__Bonus-Satisfy.mp3',
  'assets/sounds/chapter2/2-39__Bonus-Miss.mp3',
  'assets/sounds/chapter2/2-40__Bonus-World.mp3',

  // Chapter 3
  'assets/sounds/chapter3/3-01__Drum1_Ballet_A.mp3',
  'assets/sounds/chapter3/3-02__Drum2_Kick_A.mp3',
  'assets/sounds/chapter3/3-03__Drum3_Snare_A.mp3',
  'assets/sounds/chapter3/3-04__Drum4_Lead_A.mp3',
  'assets/sounds/chapter3/3-05__Drum5_Charley_A.mp3',
  'assets/sounds/chapter3/3-06__Effet1_Long_A.mp3',
  'assets/sounds/chapter3/3-07__Effet1_Long_B.mp3',
  'assets/sounds/chapter3/3-08__Effet2_Daft1_A.mp3',
  'assets/sounds/chapter3/3-09__Effet3_Tududu_A.mp3',
  'assets/sounds/chapter3/3-10__Effet4_Daft2_A.mp3',
  'assets/sounds/chapter3/3-11__Effet5_Rythme_A.mp3',
  'assets/sounds/chapter3/3-12__Effet5_Rythme_B.mp3',
  'assets/sounds/chapter3/3-13__Melo1_Tuu_A.mp3',
  'assets/sounds/chapter3/3-14__Melo2_Indien_A.mp3',
  'assets/sounds/chapter3/3-15__Melo3_Armo_A.mp3',
  'assets/sounds/chapter3/3-16__Melo4_Clav_A.mp3',
  'assets/sounds/chapter3/3-17__Melo4_Clav_B.mp3',
  'assets/sounds/chapter3/3-18__Melo5_Siffle_A.mp3',
  'assets/sounds/chapter3/3-19__Voix1_Waya_A.mp3',
  'assets/sounds/chapter3/3-20__Voix2_Ride_A.mp3',
  'assets/sounds/chapter3/3-21__Voix2_Ride_B.mp3',
  'assets/sounds/chapter3/3-22__Voix3_Over_A.mp3',
  'assets/sounds/chapter3/3-23__Voix3_Over_B.mp3',
  'assets/sounds/chapter3/3-24__Voix4_Colors_A.mp3',
  'assets/sounds/chapter3/3-25__Voix5_Sunrise_A.mp3',
  'assets/sounds/chapter3/3-26__Voix5_Sunrise_B.mp3',
  'assets/sounds/chapter3/3-27__Predrop.mp3',
  'assets/sounds/chapter3/3-28__Bonus-Dance.mp3',
  'assets/sounds/chapter3/3-29__Bonus-Child.mp3',
  'assets/sounds/chapter3/3-30__Bonus-Sunrise.mp3',

  // Chapter 4
  'assets/sounds/chapter4/4-01__Drum1_Kick_A.mp3',
  'assets/sounds/chapter4/4-02__Drum1_Kick_B.mp3',
  'assets/sounds/chapter4/4-03__Drum2_Snare_A.mp3',
  'assets/sounds/chapter4/4-04__Drum2_Snare_B.mp3',
  'assets/sounds/chapter4/4-05__Drum3_Touti_A.mp3',
  'assets/sounds/chapter4/4-06__Drum4_Charley_A.mp3',
  'assets/sounds/chapter4/4-07__Drum5_Chatom_A.mp3',
  'assets/sounds/chapter4/4-08__Drum5_Chatom_B.mp3',
  'assets/sounds/chapter4/4-09__Effect1_Bass_A.mp3',
  'assets/sounds/chapter4/4-10__Effect1_Bass_B.mp3',
  'assets/sounds/chapter4/4-11__Effect2_Enigmatic_A.mp3',
  'assets/sounds/chapter4/4-12__Effect3_Cry_A.mp3',
  'assets/sounds/chapter4/4-13__Effect4_Odoyouno_A.mp3',
  'assets/sounds/chapter4/4-14__Effect5_Oua_A.mp3',
  'assets/sounds/chapter4/4-15__Melo1_Toun_A.mp3',
  'assets/sounds/chapter4/4-16__Melo1_Toun_B.mp3',
  'assets/sounds/chapter4/4-17__Melo2_Flute_A.mp3',
  'assets/sounds/chapter4/4-18__Melo2_Flute_B.mp3',
  'assets/sounds/chapter4/4-19__Melo3_Neou_A.mp3',
  'assets/sounds/chapter4/4-20__Melo3_Neou_B.mp3',
  'assets/sounds/chapter4/4-21__Melo4_Hu_A.mp3',
  'assets/sounds/chapter4/4-22__Melo5_Ah_A.mp3',
  'assets/sounds/chapter4/4-23__Voice1_Feel_A.mp3',
  'assets/sounds/chapter4/4-24__Voice1_Feel_B.mp3',
  'assets/sounds/chapter4/4-25__Voice2_Chillin_A.mp3',
  'assets/sounds/chapter4/4-26__Voice3_Yeah_A.mp3',
  'assets/sounds/chapter4/4-27__Voice4_Filback_A.mp3',
  'assets/sounds/chapter4/4-28__Voice4_Filback_B.mp3',
  'assets/sounds/chapter4/4-29__Voice5_Teylo_A.mp3',
  'assets/sounds/chapter4/4-30__Bonus_Predrop.mp3',
  'assets/sounds/chapter4/4-31__Bonus1_Love.mp3',
  'assets/sounds/chapter4/4-32__Bonus2_Follow.mp3',
  'assets/sounds/chapter4/4-33__Bonus3_Eagle.mp3',

  // Chapter 5
  'assets/sounds/chapter5/5-01. Poum A.mp3',
  'assets/sounds/chapter5/5-02. Creuki A.mp3',
  'assets/sounds/chapter5/5-03. Shaka A.mp3',
  'assets/sounds/chapter5/5-04. Chouk A.mp3',
  'assets/sounds/chapter5/5-05. Kaliak A.mp3',
  'assets/sounds/chapter5/5-06. Tek A.mp3',
  'assets/sounds/chapter5/5-07. Tuk A.mp3',
  'assets/sounds/chapter5/5-08. Teung A.mp3',
  'assets/sounds/chapter5/5-09. Ting A.mp3',
  'assets/sounds/chapter5/5-10. Kougou A.mp3',
  'assets/sounds/chapter5/5-11. Parimba A.mp3',
  'assets/sounds/chapter5/5-12. Coloko A.mp3',
  'assets/sounds/chapter5/5-13. Clav A.mp3',
  'assets/sounds/chapter5/5-14. Tromp A.mp3',
  'assets/sounds/chapter5/5-15. Trompolo A.mp3',
  'assets/sounds/chapter5/5-16. Bass A.mp3',
  'assets/sounds/chapter5/5-17. Wa A.mp3',
  'assets/sounds/chapter5/5-18. Ya A.mp3',
  'assets/sounds/chapter5/5-19. Palapa A.mp3',
  'assets/sounds/chapter5/5-20. Oh A.mp3',
  'assets/sounds/chapter5/5-21. Bonus-Felicidade.mp3',
  'assets/sounds/chapter5/5-22. Bonus-Chegou.mp3',
  'assets/sounds/chapter5/5-23. Bonus-Musica.mp3',

  // Chapter 6
  'assets/sounds/chapter6/6-01. Icka.mp3',
  'assets/sounds/chapter6/6-02. Narea.mp3',
  'assets/sounds/chapter6/6-03. Anyea.mp3',
  'assets/sounds/chapter6/6-04. Uctuca.mp3',
  'assets/sounds/chapter6/6-05. Reaka.mp3',
  'assets/sounds/chapter6/6-06. Ribassea.mp3',
  'assets/sounds/chapter6/6-07. Istotuta.mp3',
  'assets/sounds/chapter6/6-08. Crewa.mp3',
  'assets/sounds/chapter6/6-09. Haolina.mp3',
  'assets/sounds/chapter6/6-10. Howera.mp3',
  'assets/sounds/chapter6/6-11. Assea.mp3',
  'assets/sounds/chapter6/6-12. Oua.mp3',
  'assets/sounds/chapter6/6-13. Lava.mp3',
  'assets/sounds/chapter6/6-14. Yntha.mp3',
  'assets/sounds/chapter6/6-15. Aha.mp3',
  'assets/sounds/chapter6/6-16. Urrya.mp3',
  'assets/sounds/chapter6/6-17. Ooda.mp3',
  'assets/sounds/chapter6/6-18. Inda.mp3',
  'assets/sounds/chapter6/6-19. Ahaa.mp3',
  'assets/sounds/chapter6/6-20. Owa.mp3',
  'assets/sounds/chapter6/6-21. Onus-Alive.mp3',
  'assets/sounds/chapter6/6-22. Redrop-Busta.mp3',
  'assets/sounds/chapter6/6-23. Onus-Busta.mp3',
  'assets/sounds/chapter6/6-24. Redrop-Vr.mp3',
  'assets/sounds/chapter6/6-25. Onus-Vr.mp3',

  // Chapter 7
  'assets/sounds/chapter7/7-01. Lead A.mp3',
  'assets/sounds/chapter7/7-02. Pouin A.mp3',
  'assets/sounds/chapter7/7-03. Pouin B.mp3',
  'assets/sounds/chapter7/7-04. Tung A.mp3',
  'assets/sounds/chapter7/7-05. Tabla A.mp3',
  'assets/sounds/chapter7/7-06. Tuduki A.mp3',
  'assets/sounds/chapter7/7-07. Bass A.mp3',
  'assets/sounds/chapter7/7-08. Bass B.mp3',
  'assets/sounds/chapter7/7-09. Bourdon A.mp3',
  'assets/sounds/chapter7/7-10. Campan A.mp3',
  'assets/sounds/chapter7/7-11. Kum A.mp3',
  'assets/sounds/chapter7/7-12. Kum B.mp3',
  'assets/sounds/chapter7/7-13. String A.mp3',
  'assets/sounds/chapter7/7-14. String B.mp3',
  'assets/sounds/chapter7/7-15. Citar A.mp3',
  'assets/sounds/chapter7/7-16. Guit A.mp3',
  'assets/sounds/chapter7/7-17. Tromp A.mp3',
  'assets/sounds/chapter7/7-18. Tromp B.mp3',
  'assets/sounds/chapter7/7-19. Taoung A.mp3',
  'assets/sounds/chapter7/7-20. Sifle A.mp3',
  'assets/sounds/chapter7/7-21. Sifle B.mp3',
  'assets/sounds/chapter7/7-22. Djindr A.mp3',
  'assets/sounds/chapter7/7-23. Djinga A.mp3',
  'assets/sounds/chapter7/7-24. Djinta A.mp3',
  'assets/sounds/chapter7/7-25. Jeevan A.mp3',
  'assets/sounds/chapter7/7-26. Jeevan B.mp3',
  'assets/sounds/chapter7/7-27. Yaha A.mp3',
  'assets/sounds/chapter7/7-28. Yaha B.mp3',
  'assets/sounds/chapter7/7-29. Bonus Kofitez.mp3',
  'assets/sounds/chapter7/7-30. Predrop Sapna.mp3',
  'assets/sounds/chapter7/7-31. Bonus Sapna.mp3',
  'assets/sounds/chapter7/7-32. Bonus Kabikabi.mp3',

  // Chapter 8
  'assets/sounds/chapter8/8-01. Atlanta A.mp3',
  'assets/sounds/chapter8/8-02. Atlanta B.mp3',
  'assets/sounds/chapter8/8-03. Tuctom A.mp3',
  'assets/sounds/chapter8/8-04. Tuctom B.mp3',
  'assets/sounds/chapter8/8-05. Foubreak A.mp3',
  'assets/sounds/chapter8/8-06. Foubreak B.mp3',
  'assets/sounds/chapter8/8-07. Koukaki A.mp3',
  'assets/sounds/chapter8/8-08. Koungou A.mp3',
  'assets/sounds/chapter8/8-09. Bass A.mp3',
  'assets/sounds/chapter8/8-10. Bass B.mp3',
  'assets/sounds/chapter8/8-11. Monk A.mp3',
  'assets/sounds/chapter8/8-12. Monk B.mp3',
  'assets/sounds/chapter8/8-13. Sonar A.mp3',
  'assets/sounds/chapter8/8-14. Souffle A.mp3',
  'assets/sounds/chapter8/8-15. Souffle B.mp3',
  'assets/sounds/chapter8/8-16. Epifle A.mp3',
  'assets/sounds/chapter8/8-17. Epifle B.mp3',
  'assets/sounds/chapter8/8-18. Arpeg A.mp3',
  'assets/sounds/chapter8/8-19. Arpeg B.mp3',
  'assets/sounds/chapter8/8-20. Tromp A.mp3',
  'assets/sounds/chapter8/8-21. Tromp B.mp3',
  'assets/sounds/chapter8/8-22. Pizzi A.mp3',
  'assets/sounds/chapter8/8-23. Pizzi B.mp3',
  'assets/sounds/chapter8/8-24. Organ A.mp3',
  'assets/sounds/chapter8/8-25. Organ B.mp3',
  'assets/sounds/chapter8/8-26. Synth A.mp3',
  'assets/sounds/chapter8/8-27. Synth B.mp3',
  'assets/sounds/chapter8/8-28. Follow A.mp3',
  'assets/sounds/chapter8/8-29. Follow B.mp3',
  'assets/sounds/chapter8/8-30. Choir A.mp3',
  'assets/sounds/chapter8/8-31. Choir B.mp3',
  'assets/sounds/chapter8/8-32. Houhou A.mp3',
  'assets/sounds/chapter8/8-33. Houhou B.mp3',
  'assets/sounds/chapter8/8-34. Reach A.mp3',
  'assets/sounds/chapter8/8-35. Reach B.mp3',
  'assets/sounds/chapter8/8-36. Believe A.mp3',
  'assets/sounds/chapter8/8-37. Believe B.mp3',
  'assets/sounds/chapter8/8-38. Bonus Riviera.mp3',
  'assets/sounds/chapter8/8-39. Bonus Zemetekile.mp3',
  'assets/sounds/chapter8/8-40. Bonus Cumulor.mp3',

  // Chapter 9
  'assets/sounds/chapter9/9-01. Boo 9 A.mp3',
  'assets/sounds/chapter9/9-02. Boo 9 B.mp3',
  'assets/sounds/chapter9/9-03. Kevin A.mp3',
  'assets/sounds/chapter9/9-04. Kevin B.mp3',
  'assets/sounds/chapter9/9-05. Double K A.mp3',
  'assets/sounds/chapter9/9-06. Double K B.mp3',
  'assets/sounds/chapter9/9-07. Blue Gt A.mp3',
  'assets/sounds/chapter9/9-08. Mj 182 A.mp3',
  'assets/sounds/chapter9/9-09. Boom Fuzz A.mp3',
  'assets/sounds/chapter9/9-10. Boom Fuzz B.mp3',
  'assets/sounds/chapter9/9-11. Asap Bee A.mp3',
  'assets/sounds/chapter9/9-12. Asap Bee B.mp3',
  'assets/sounds/chapter9/9-13. M O G A.mp3',
  'assets/sounds/chapter9/9-14. M O G B.mp3',
  'assets/sounds/chapter9/9-15. Arashi A.mp3',
  'assets/sounds/chapter9/9-16. Arashi B.mp3',
  'assets/sounds/chapter9/9-17. Big Duke A.mp3',
  'assets/sounds/chapter9/9-18. Big Duke B.mp3',
  'assets/sounds/chapter9/9-19. Swingy A.mp3',
  'assets/sounds/chapter9/9-20. Swingy B.mp3',
  'assets/sounds/chapter9/9-21. D Invaders A.mp3',
  'assets/sounds/chapter9/9-22. D Invaders B.mp3',
  'assets/sounds/chapter9/9-23. Doo Doo A.mp3',
  'assets/sounds/chapter9/9-24. 8 Bit A.mp3',
  'assets/sounds/chapter9/9-25. 8 Bit B.mp3',
  'assets/sounds/chapter9/9-26. Kc Glow A.mp3',
  'assets/sounds/chapter9/9-27. Kc Glow B.mp3',
  'assets/sounds/chapter9/9-28. El Cool P A.mp3',
  'assets/sounds/chapter9/9-29. El Cool P B.mp3',
  'assets/sounds/chapter9/9-30. Memphis A.mp3',
  'assets/sounds/chapter9/9-31. Memphis B.mp3',
  'assets/sounds/chapter9/9-32. Jogg D A.mp3',
  'assets/sounds/chapter9/9-33. Jogg D B.mp3',
  'assets/sounds/chapter9/9-34. Scooter A.mp3',
  'assets/sounds/chapter9/9-35. Scooter B.mp3',
  'assets/sounds/chapter9/9-36. Lil Blaze A.mp3',
  'assets/sounds/chapter9/9-37. Lil Blaze B.mp3',
  'assets/sounds/chapter9/9-38. Predrop Flow.mp3',
  'assets/sounds/chapter9/9-39. Bonus Flow.mp3',
  'assets/sounds/chapter9/9-40. Predrop Urfo.mp3',
  'assets/sounds/chapter9/9-41. Bonus Urfo.mp3',
  'assets/sounds/chapter9/9-42. Bonus Bdb.mp3'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return Promise.allSettled(
        ALL_ASSETS.map((asset) => cache.add(asset))
      );
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }

      if (req.mode === 'navigate') {
        return caches.match('./index.html').then((fallback) => fallback || caches.match('./'));
      }

      return fetch(req);
    })
  );
});